### ISSUE TITLE
Invalid environment marker: python_version<"2.7" due to extra colon

### ISSUE THREAD

**Issue by ejames** [testing-cabal/funcsigs#22]
An erroneous colon in 6848ca897c141cdf0747b622b9d020585c74cef4, the fix to #18, causes setup.py to fail:

```
$ python setup.py develop
error in funcsigs setup command: Invalid environment marker: python_version<"2.7"
```

**Comment by rbtcollins** [comment]
See issue #21 - the : is valid, but your setuptools is too old.

**Comment by legrostdg** [comment]
I actually have the same problem:

```
$ python setup.py build
warning: no files found matching '*' under directory 'setuptools/_vendor'

Installed /home/user/builds/funcsigs/setuptools-24.0.2-py2.7.egg
error in funcsigs setup command: Invalid environment marker: python_version<"2.7"
```

So, funcsigs installs setuptools-24.0.2, but fails on `:python_version<"2.7"`. With `python_version<"2.7"` it builds.

**Comment by legrostdg** [comment]
Do you have any clues to solve this? As far as I can see, funcsigs installs setuptools-24.0.2, so should work with `:python_version<"2.7"`... Is there any downsides in reverting it to `python_version<"2.7"`?

**Comment by rbtcollins** [comment]
Demand-installed setuptools won't work because setuptools is already loaded when the dependencies are processed; with a pyproject.toml it should work but that hasn't been implemented into pip etc yet.

With 'python_version<"2.7"' that becomes the name of an extra, rather than a conditional dependency - the semantics are entirely different.
