### ISSUE TITLE
signature() does not provide ability to NOT follow wrapped

### ISSUE THREAD

**Issue by tailg8nj** [testing-cabal/funcsigs#33]
If you see the API for inspect.signature, you will see it supports a follow_unwrapped argument. This backport does not provide the option of following the wrap chain or not. https://docs.python.org/3/library/inspect.html#inspect.signature

**Comment by rbtcollins** [comment]
This needs to be backported.

**Comment by smarie** [comment]
I was about to ask for it too :) - thanks for creating the ticket. 

For the record I use the `__wrapped__` signature trick in [decopatch](https://smarie.github.io/python-decopatch/), so that exposed decorators can both have a generic signature from the code perspective, but a nice-looking signature from users perspective.

As of today I have to create specific tests for python 2.7 because of this `funcsigs` behaviour.

**Comment by smarie** [comment]
Done (see PR #37). Maybe this can ship together with the `bound.apply_defaults` fix that you recently made, in a new version ? This would be gladly appreciated as I have a few developments pending that are currently blocked in continuous integration on python 2 because of this.

Thanks for maintaining this package !

**Comment by smarie** [comment]
Hi,
Any news about merging the PR that fixes this issue ? https://github.com/testing-cabal/funcsigs/pull/37
Thanks!

**Comment by rbtcollins** [comment]
We need some additional work done to fix CI - remove obsolete failing python versions; that kind of thing but all the current versions were passing so I've merged the PR

**Comment by smarie** [comment]
Great, thanks very much @rbtcollins !
